// Kya Khaye seed data — Phase 2.
// Heritage Punjabi collection (heritage='punjabi-classic') + everyday dishes.
// Idempotent: seedRecipes(pool) skips recipes whose name already exists.
const RECIPES = [
  // ---------------- HERITAGE: punjabi-classic ----------------
  {
    name: 'Sarson da Saag + Makki di Roti',
    description: 'Slow-cooked mustard greens with corn-flour rotis — the winter throne of Punjabi kitchens.',
    heritage: 'punjabi-classic',
    health_note: 'Mustard greens are rich in iron and fibre; slow cooking with a spoon of desi ghee is how winters were survived back home.',
    meal_types: ['lunch', 'dinner'], diet: 'veg', servings: 4, prep_minutes: 60,
    protein_g: 9, carbs_g: 38, fat_g: 14, calories: 370,
    ingredients: [
      { name: 'mustard greens', qty: 1, unit: 'kg' },
      { name: 'spinach', qty: 250, unit: 'g' },
      { name: 'corn flour', qty: 2, unit: 'cups' },
      { name: 'onion', qty: 2, unit: 'pcs' },
      { name: 'ginger', qty: 2, unit: 'inch' },
      { name: 'garlic', qty: 6, unit: 'pcs' },
      { name: 'green chili', qty: 2, unit: 'pcs' },
      { name: 'ghee', qty: 3, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Wash and roughly chop the mustard greens and spinach. Boil with salt until soft, about 20 minutes.',
      'Mash coarsely with a wooden churner (madhaani) — never a smooth puree.',
      'Temper ghee with chopped onion, ginger, garlic and green chili; pour over the saag and simmer 10 minutes.',
      'Knead corn flour with warm water and salt; pat into rotis and roast on a hot tawa with ghee.',
      'Serve saag with white butter, jaggery and makki di roti.',
    ],
  },
  {
    name: 'Dal Makhani',
    description: 'Black lentils and kidney beans simmered low and slow in tomato-butter gravy.',
    heritage: 'punjabi-classic',
    health_note: 'Black lentils are protein-dense; the long slow simmer is the original high-protein comfort food.',
    meal_types: ['lunch', 'dinner'], diet: 'veg', servings: 4, prep_minutes: 50,
    protein_g: 12, carbs_g: 28, fat_g: 18, calories: 320,
    ingredients: [
      { name: 'black lentils', qty: 1, unit: 'cups' },
      { name: 'kidney beans', qty: 0.25, unit: 'cups' },
      { name: 'tomato', qty: 3, unit: 'pcs' },
      { name: 'butter', qty: 3, unit: 'tbsp' },
      { name: 'cream', qty: 0.25, unit: 'cups' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'garlic', qty: 4, unit: 'pcs' },
      { name: 'garam masala', qty: 1, unit: 'tsp' },
      { name: 'red chili powder', qty: 0.5, unit: 'tsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Soak lentils and kidney beans overnight; pressure cook until completely soft.',
      'Blend tomatoes to a puree; sauté with ginger-garlic until the oil separates.',
      'Add the cooked dal, salt and spices; simmer on low 30 minutes, stirring often.',
      'Finish with butter and cream. Rest 10 minutes before serving.',
    ],
  },
  {
    name: 'Rajma Chawal',
    description: 'Kidney beans in spiced tomato gravy over steamed basmati — the Sunday staple.',
    heritage: 'punjabi-classic',
    health_note: 'Kidney beans plus rice make a complete protein — the Sunday staple that fuelled generations.',
    meal_types: ['lunch', 'dinner'], diet: 'veg', servings: 4, prep_minutes: 45,
    protein_g: 15, carbs_g: 68, fat_g: 8, calories: 400,
    ingredients: [
      { name: 'kidney beans', qty: 1.5, unit: 'cups' },
      { name: 'rice', qty: 2, unit: 'cups' },
      { name: 'onion', qty: 2, unit: 'pcs' },
      { name: 'tomato', qty: 3, unit: 'pcs' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'garlic', qty: 5, unit: 'pcs' },
      { name: 'cumin seeds', qty: 1, unit: 'tsp' },
      { name: 'garam masala', qty: 1, unit: 'tsp' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Soak rajma overnight; pressure cook with salt until tender.',
      'Sauté cumin, onion, ginger-garlic; add tomato puree and spices; cook till oil separates.',
      'Add rajma with its cooking water; simmer 20 minutes until thick.',
      'Serve over steamed basmati with onion rings and lemon.',
    ],
  },
  {
    name: 'Amritsari Chole',
    description: 'Dark, tangy chickpeas — the taste of Amritsar in a kadhai.',
    heritage: 'punjabi-classic',
    health_note: 'Chickpeas pack protein and fibre — the fuel of farmers, in a bowl.',
    meal_types: ['lunch', 'dinner'], diet: 'veg', servings: 4, prep_minutes: 40,
    protein_g: 14, carbs_g: 52, fat_g: 10, calories: 350,
    ingredients: [
      { name: 'chickpeas', qty: 1.5, unit: 'cups' },
      { name: 'onion', qty: 2, unit: 'pcs' },
      { name: 'tomato', qty: 2, unit: 'pcs' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'garlic', qty: 4, unit: 'pcs' },
      { name: 'cumin seeds', qty: 1, unit: 'tsp' },
      { name: 'coriander powder', qty: 1, unit: 'tbsp' },
      { name: 'garam masala', qty: 1, unit: 'tsp' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Soak chickpeas overnight; pressure cook until soft.',
      'Brown onions deeply in oil; add ginger-garlic and tomato.',
      'Add spices and cooked chole; simmer 15 minutes, mashing a few for thickness.',
      'Serve with bhature, kulcha, or jeera rice.',
    ],
  },
  {
    name: 'Aloo Paratha',
    description: 'Whole-wheat flatbreads stuffed with spiced mashed potato, roasted in ghee.',
    heritage: 'punjabi-classic',
    health_note: 'Whole-wheat slow carbs with potato — the breakfast that carried long mornings in the fields.',
    meal_types: ['breakfast'], diet: 'veg', servings: 4, prep_minutes: 30,
    protein_g: 8, carbs_g: 55, fat_g: 12, calories: 370,
    ingredients: [
      { name: 'whole wheat flour', qty: 2, unit: 'cups' },
      { name: 'potato', qty: 4, unit: 'pcs' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'green chili', qty: 2, unit: 'pcs' },
      { name: 'coriander leaves', qty: 0.25, unit: 'cups' },
      { name: 'carom seeds', qty: 0.5, unit: 'tsp' },
      { name: 'ghee', qty: 3, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Boil, peel and mash potatoes; mix with onion, chili, coriander, carom seeds and salt.',
      'Knead atta into a soft dough; rest 15 minutes.',
      'Stuff each dough ball with potato mix; roll gently and roast on tawa with ghee till golden.',
      'Serve with dahi, white butter and pickle.',
    ],
  },
  {
    name: 'Kadhi Pakora',
    description: 'Tangy yogurt curry with crisp onion pakoras floating in it.',
    heritage: 'punjabi-classic',
    health_note: 'Yogurt-based and light — probiotics and comfort in one kadhai, just like nani made.',
    meal_types: ['lunch', 'dinner'], diet: 'veg', servings: 4, prep_minutes: 35,
    protein_g: 10, carbs_g: 30, fat_g: 14, calories: 290,
    ingredients: [
      { name: 'yogurt', qty: 2, unit: 'cups' },
      { name: 'gram flour', qty: 0.5, unit: 'cups' },
      { name: 'onion', qty: 2, unit: 'pcs' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'mustard seeds', qty: 1, unit: 'tsp' },
      { name: 'cumin seeds', qty: 1, unit: 'tsp' },
      { name: 'curry leaves', qty: 10, unit: 'pcs' },
      { name: 'oil', qty: 0.5, unit: 'cups' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Whisk yogurt, gram flour, turmeric, salt and 4 cups water till smooth; simmer 20 minutes, stirring.',
      'Mix sliced onion with gram flour, salt and water; fry spoonfuls into crisp pakoras.',
      'Temper mustard, cumin and curry leaves in oil; pour into the kadhi.',
      'Drop in pakoras, simmer 5 minutes, serve with rice.',
    ],
  },
  {
    name: 'Baingan Bharta',
    description: 'Fire-roasted eggplant mashed with peas and tomato.',
    heritage: 'punjabi-classic',
    health_note: 'Fire-roasted and light — smoky fibre-rich food with almost no fuss.',
    meal_types: ['dinner'], diet: 'veg', servings: 4, prep_minutes: 30,
    protein_g: 5, carbs_g: 16, fat_g: 12, calories: 190,
    ingredients: [
      { name: 'eggplant', qty: 2, unit: 'pcs' },
      { name: 'peas', qty: 0.5, unit: 'cups' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'tomato', qty: 2, unit: 'pcs' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'green chili', qty: 1, unit: 'pcs' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Roast whole eggplants over open flame till skin chars and flesh collapses; peel and mash.',
      'Sauté onion, ginger, chili and tomato till soft.',
      'Add mashed brinjal and peas; cook 10 minutes till smoky and thick.',
      'Serve with hot rotis and a dollop of ghee.',
    ],
  },
  {
    name: 'Dal Tadka',
    description: 'Everyday yellow dal with a sizzling ghee-garlic tempering.',
    heritage: 'punjabi-classic',
    health_note: 'The everyday dal — light, digestible daily protein with a ghee tadka.',
    meal_types: ['lunch', 'dinner'], diet: 'veg', servings: 4, prep_minutes: 25,
    protein_g: 13, carbs_g: 38, fat_g: 8, calories: 280,
    ingredients: [
      { name: 'pigeon pea lentils', qty: 1, unit: 'cups' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'tomato', qty: 1, unit: 'pcs' },
      { name: 'garlic', qty: 6, unit: 'pcs' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'cumin seeds', qty: 1, unit: 'tsp' },
      { name: 'red chili powder', qty: 0.5, unit: 'tsp' },
      { name: 'ghee', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Pressure cook dal with turmeric and salt till soft; whisk smooth.',
      'Sauté onion and tomato till soft; stir into the dal and simmer.',
      'Heat ghee, crackle cumin, fry sliced garlic and red chili till golden.',
      'Pour the tadka over the dal, cover 2 minutes, serve.',
    ],
  },
  {
    name: 'Kala Chana Masala',
    description: 'Black chickpeas in a dry-ish onion-tomato masala.',
    heritage: 'punjabi-classic',
    health_note: 'Black chickpeas are iron-rich with slow-release energy — navratri fasting food for a reason.',
    meal_types: ['lunch', 'snack'], diet: 'vegan', servings: 4, prep_minutes: 35,
    protein_g: 14, carbs_g: 44, fat_g: 8, calories: 300,
    ingredients: [
      { name: 'black chickpeas', qty: 1.5, unit: 'cups' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'tomato', qty: 2, unit: 'pcs' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'cumin seeds', qty: 1, unit: 'tsp' },
      { name: 'coriander powder', qty: 1, unit: 'tsp' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Soak kala chana overnight; pressure cook with salt till tender.',
      'Sauté cumin, onion, ginger; add tomato and spices.',
      'Toss in the chana with a splash of cooking water; simmer 10 minutes.',
      'Finish with lemon and coriander leaves.',
    ],
  },
  {
    name: 'Aloo Gobi',
    description: 'Potato and cauliflower tossed with ginger, turmeric and peas.',
    heritage: 'punjabi-classic',
    health_note: 'Humble potato-cauliflower — simple, filling, honest food with barely any oil.',
    meal_types: ['lunch', 'dinner'], diet: 'vegan', servings: 4, prep_minutes: 25,
    protein_g: 6, carbs_g: 32, fat_g: 9, calories: 230,
    ingredients: [
      { name: 'potato', qty: 3, unit: 'pcs' },
      { name: 'cauliflower', qty: 1, unit: 'pcs' },
      { name: 'peas', qty: 0.5, unit: 'cups' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'cumin seeds', qty: 1, unit: 'tsp' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cut potato and cauliflower into bite-size pieces.',
      'Crackle cumin in oil; sauté onion and ginger till golden.',
      'Add vegetables, turmeric, salt and a sprinkle of water; cover and cook 15 minutes.',
      'Stir in peas, cook 3 more minutes, serve with rotis.',
    ],
  },
  {
    name: 'Paneer Bhurji',
    description: 'Crumbled paneer scrambled with onion, tomato and peas.',
    heritage: 'punjabi-classic',
    health_note: 'Fresh paneer crumbled with peas — a protein punch that starts the day right.',
    meal_types: ['breakfast'], diet: 'veg', servings: 4, prep_minutes: 15,
    protein_g: 18, carbs_g: 10, fat_g: 16, calories: 260,
    ingredients: [
      { name: 'paneer', qty: 400, unit: 'g' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'tomato', qty: 2, unit: 'pcs' },
      { name: 'peas', qty: 0.5, unit: 'cups' },
      { name: 'green chili', qty: 1, unit: 'pcs' },
      { name: 'turmeric', qty: 0.25, unit: 'tsp' },
      { name: 'garam masala', qty: 0.5, unit: 'tsp' },
      { name: 'oil', qty: 1, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Crumble paneer coarsely by hand.',
      'Sauté onion, chili and tomato till soft; add turmeric and peas.',
      'Fold in paneer and salt; cook 3 minutes — do not overcook.',
      'Sprinkle garam masala and coriander; serve with toast or paratha.',
    ],
  },
  {
    name: 'Mix Sabzi',
    description: 'Seasonal vegetables tossed together — whatever the mandi gave that day.',
    heritage: 'punjabi-classic',
    health_note: 'Whatever the season gave — the original eat-the-rainbow, zero waste cooking.',
    meal_types: ['dinner'], diet: 'vegan', servings: 4, prep_minutes: 25,
    protein_g: 6, carbs_g: 24, fat_g: 9, calories: 200,
    ingredients: [
      { name: 'carrot', qty: 2, unit: 'pcs' },
      { name: 'potato', qty: 2, unit: 'pcs' },
      { name: 'cauliflower', qty: 0.5, unit: 'pcs' },
      { name: 'peas', qty: 0.5, unit: 'cups' },
      { name: 'capsicum', qty: 1, unit: 'pcs' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Chop all vegetables into similar-size pieces.',
      'Sauté onion in oil; add hard vegetables first with turmeric and salt.',
      'Cover and cook 12 minutes; add capsicum and peas for the last 5.',
      'Serve hot with dal and rotis.',
    ],
  },
  {
    name: 'Saadi Lassi',
    description: 'Thick churned yogurt, lightly sweetened, with a malai top.',
    heritage: 'punjabi-classic',
    health_note: 'Churned dahi — natural probiotics and cool energy; the original desi cooler.',
    meal_types: ['breakfast', 'snack'], diet: 'veg', servings: 4, prep_minutes: 10,
    protein_g: 8, carbs_g: 24, fat_g: 6, calories: 180,
    ingredients: [
      { name: 'yogurt', qty: 3, unit: 'cups' },
      { name: 'milk', qty: 1, unit: 'cups' },
      { name: 'sugar', qty: 3, unit: 'tbsp' },
      { name: 'cardamom', qty: 0.25, unit: 'tsp' },
    ],
    steps: [
      'Churn yogurt with milk till frothy.',
      'Whisk in sugar and cardamom.',
      'Pour into tall glasses; top with a spoon of malai.',
      'Serve chilled, ideally in a kulhad.',
    ],
  },
  {
    name: 'Bajra Khichdi',
    description: 'Pearl millet and moong dal cooked into a soft, ghee-tempered one-pot.',
    heritage: 'punjabi-classic',
    health_note: 'Millet plus dal — the ancient one-pot grandmothers trusted for strength and digestion.',
    meal_types: ['dinner'], diet: 'veg', servings: 4, prep_minutes: 40,
    protein_g: 11, carbs_g: 52, fat_g: 9, calories: 330,
    ingredients: [
      { name: 'pearl millet', qty: 1, unit: 'cups' },
      { name: 'moong lentils', qty: 0.5, unit: 'cups' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'cumin seeds', qty: 1, unit: 'tsp' },
      { name: 'ghee', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Soak bajra 4 hours (or overnight); pressure cook with dal, turmeric and salt till soft.',
      'Mash lightly for a porridge texture.',
      'Temper cumin and onion in ghee; stir through.',
      'Serve with kadhi or dahi and papad.',
    ],
  },
  {
    name: 'Methi Paratha',
    description: 'Whole-wheat parathas kneaded with fresh fenugreek leaves.',
    heritage: 'punjabi-classic',
    health_note: 'Fenugreek greens kneaded into atta — dadi-approved for blood sugar and strength.',
    meal_types: ['breakfast'], diet: 'veg', servings: 4, prep_minutes: 25,
    protein_g: 9, carbs_g: 48, fat_g: 10, calories: 320,
    ingredients: [
      { name: 'whole wheat flour', qty: 2, unit: 'cups' },
      { name: 'fenugreek leaves', qty: 2, unit: 'cups' },
      { name: 'carom seeds', qty: 0.5, unit: 'tsp' },
      { name: 'turmeric', qty: 0.25, unit: 'tsp' },
      { name: 'ghee', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Chop methi fine; knead with atta, salt, carom seeds and water into a soft dough.',
      'Rest 15 minutes; roll into parathas.',
      'Roast on tawa with ghee till crisp spots appear.',
      'Serve with dahi and pickle.',
    ],
  },
  {
    name: 'Aloo Kulcha (Tawa)',
    description: 'Soft leavened kulchas stuffed with spiced potato, made on a tawa.',
    heritage: 'punjabi-classic',
    health_note: 'Amritsar on a griddle — hearty and satisfying; pair with chole for the full experience.',
    meal_types: ['breakfast', 'lunch'], diet: 'veg', servings: 4, prep_minutes: 35,
    protein_g: 10, carbs_g: 58, fat_g: 9, calories: 350,
    ingredients: [
      { name: 'all-purpose flour', qty: 2, unit: 'cups' },
      { name: 'yogurt', qty: 0.5, unit: 'cups' },
      { name: 'potato', qty: 3, unit: 'pcs' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'coriander leaves', qty: 0.25, unit: 'cups' },
      { name: 'butter', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Knead flour with yogurt, salt and water into a soft dough; rest 1 hour.',
      'Mash boiled potatoes with onion, coriander and salt.',
      'Stuff, roll gently, and cook on a hot tawa till puffed and spotted.',
      'Brush with butter; serve with chole.',
    ],
  },
  {
    name: 'Gajar ka Halwa',
    description: 'Winter carrots slow-reduced in milk and ghee, studded with nuts.',
    heritage: 'punjabi-classic',
    health_note: 'Winter carrots and milk — the celebration sweet; enjoy in moderation, the way festivals intended.',
    meal_types: ['snack'], diet: 'veg', servings: 4, prep_minutes: 45,
    protein_g: 7, carbs_g: 42, fat_g: 16, calories: 340,
    ingredients: [
      { name: 'carrot', qty: 1, unit: 'kg' },
      { name: 'milk', qty: 3, unit: 'cups' },
      { name: 'sugar', qty: 0.5, unit: 'cups' },
      { name: 'ghee', qty: 3, unit: 'tbsp' },
      { name: 'cardamom', qty: 0.5, unit: 'tsp' },
      { name: 'mixed nuts', qty: 0.25, unit: 'cups' },
    ],
    steps: [
      'Grate carrots; cook in milk on low till the milk is absorbed.',
      'Add sugar; cook till the mixture thickens and turns glossy.',
      'Stir in ghee and cardamom; roast 5 minutes.',
      'Top with toasted nuts; serve warm.',
    ],
  },
  {
    name: 'Panjiri',
    description: 'Roasted atta, ghee, nuts and seeds — the traditional energy mix.',
    heritage: 'punjabi-classic',
    health_note: 'Atta, ghee, nuts and gond — the traditional energy mix for new mothers and hard winters.',
    meal_types: ['snack'], diet: 'veg', servings: 4, prep_minutes: 30,
    protein_g: 8, carbs_g: 36, fat_g: 20, calories: 360,
    ingredients: [
      { name: 'whole wheat flour', qty: 1.5, unit: 'cups' },
      { name: 'ghee', qty: 0.5, unit: 'cups' },
      { name: 'sugar', qty: 0.75, unit: 'cups' },
      { name: 'mixed nuts', qty: 0.5, unit: 'cups' },
      { name: 'cardamom', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Roast atta in ghee on low till deep golden and nutty, about 20 minutes.',
      'Toast the nuts separately and crush coarsely.',
      'Mix everything with sugar and cardamom off the heat.',
      'Cool and store; a spoonful is a snack.',
    ],
  },
  // ---------------- EVERYDAY ----------------
  {
    name: 'Masala Omelette',
    description: 'Fluffy omelette loaded with onion-tomato masala.',
    heritage: '', health_note: 'Eggs are complete protein — quick, cheap morning fuel.',
    meal_types: ['breakfast'], diet: 'egg', servings: 2, prep_minutes: 10,
    protein_g: 13, carbs_g: 4, fat_g: 14, calories: 200,
    ingredients: [
      { name: 'egg', qty: 4, unit: 'pcs' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'tomato', qty: 1, unit: 'pcs' },
      { name: 'green chili', qty: 1, unit: 'pcs' },
      { name: 'oil', qty: 1, unit: 'tbsp' },
      { name: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Beat eggs with salt; fold in chopped onion, tomato and chili.',
      'Heat oil; pour the mix and swirl to set.',
      'Flip once golden; cook 1 more minute.',
      'Serve with toast.',
    ],
  },
  {
    name: 'Homestyle Chicken Curry',
    description: 'Rustic onion-tomato chicken curry — the weeknight hero.',
    heritage: '', health_note: 'Lean chicken in a home-style gravy — high protein without the restaurant cream.',
    meal_types: ['dinner'], diet: 'nonveg', servings: 4, prep_minutes: 40,
    protein_g: 28, carbs_g: 10, fat_g: 16, calories: 300,
    ingredients: [
      { name: 'chicken', qty: 750, unit: 'g' },
      { name: 'onion', qty: 3, unit: 'pcs' },
      { name: 'tomato', qty: 3, unit: 'pcs' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'garlic', qty: 6, unit: 'pcs' },
      { name: 'garam masala', qty: 1, unit: 'tsp' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'oil', qty: 3, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Brown sliced onions deeply in oil.',
      'Add ginger-garlic paste and tomato; cook till oil separates.',
      'Add chicken and spices; sear 5 minutes.',
      'Add water, cover and simmer 20 minutes till tender.',
    ],
  },
  {
    name: 'Egg Curry',
    description: 'Boiled eggs simmered in a homestyle onion-tomato gravy.',
    heritage: '', health_note: 'Eggs in gravy — weeknight protein on a budget.',
    meal_types: ['dinner'], diet: 'egg', servings: 4, prep_minutes: 25,
    protein_g: 15, carbs_g: 12, fat_g: 14, calories: 250,
    ingredients: [
      { name: 'egg', qty: 8, unit: 'pcs' },
      { name: 'onion', qty: 2, unit: 'pcs' },
      { name: 'tomato', qty: 2, unit: 'pcs' },
      { name: 'ginger', qty: 1, unit: 'inch' },
      { name: 'garam masala', qty: 1, unit: 'tsp' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Boil eggs 9 minutes; peel and halve.',
      'Make an onion-tomato masala with ginger and spices.',
      'Add water for gravy; slide in the eggs and simmer 8 minutes.',
      'Serve with rice or roti.',
    ],
  },
  {
    name: 'Veg Fried Rice',
    description: 'Smoky wok-tossed rice with crunchy vegetables.',
    heritage: '', health_note: 'A fridge-cleanout hero — vegetables stay crisp and the rice stays light.',
    meal_types: ['lunch', 'dinner'], diet: 'vegan', servings: 4, prep_minutes: 20,
    protein_g: 7, carbs_g: 56, fat_g: 9, calories: 330,
    ingredients: [
      { name: 'rice', qty: 3, unit: 'cups', note: 'cooked, day-old' },
      { name: 'carrot', qty: 1, unit: 'pcs' },
      { name: 'capsicum', qty: 1, unit: 'pcs' },
      { name: 'peas', qty: 0.5, unit: 'cups' },
      { name: 'spring onion', qty: 3, unit: 'pcs' },
      { name: 'garlic', qty: 3, unit: 'pcs' },
      { name: 'soy sauce', qty: 2, unit: 'tbsp' },
      { name: 'oil', qty: 2, unit: 'tbsp' },
      { name: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Dice all vegetables small.',
      'Sizzle garlic in hot oil; toss in hard vegetables first.',
      'Add rice, soy sauce and salt; toss on high heat 3 minutes.',
      'Finish with spring onion greens.',
    ],
  },
  {
    name: 'Tomato Basil Pasta',
    description: 'Simple garlicky tomato pasta with fresh basil.',
    heritage: '', health_note: 'Pantry-friendly comfort — olive oil and tomato keep it light.',
    meal_types: ['dinner'], diet: 'veg', servings: 4, prep_minutes: 20,
    protein_g: 11, carbs_g: 62, fat_g: 11, calories: 400,
    ingredients: [
      { name: 'pasta', qty: 400, unit: 'g' },
      { name: 'tomato', qty: 5, unit: 'pcs' },
      { name: 'garlic', qty: 5, unit: 'pcs' },
      { name: 'basil', qty: 0.5, unit: 'cups' },
      { name: 'olive oil', qty: 3, unit: 'tbsp' },
      { name: 'red chili flakes', qty: 0.5, unit: 'tsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Boil pasta in salted water till al dente; save a cup of pasta water.',
      'Sizzle garlic and chili flakes in olive oil; add chopped tomatoes.',
      'Toss pasta through the sauce with a splash of pasta water.',
      'Tear in basil and serve.',
    ],
  },
  {
    name: 'Grilled Chicken Sandwich',
    description: 'Juicy grilled chicken with mint mayo in toasted bread.',
    heritage: '', health_note: 'Grilled not fried — café-style protein you can make at home.',
    meal_types: ['lunch'], diet: 'nonveg', servings: 2, prep_minutes: 15,
    protein_g: 24, carbs_g: 30, fat_g: 12, calories: 330,
    ingredients: [
      { name: 'chicken', qty: 300, unit: 'g' },
      { name: 'bread', qty: 4, unit: 'pcs' },
      { name: 'yogurt', qty: 2, unit: 'tbsp' },
      { name: 'mint leaves', qty: 0.25, unit: 'cups' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'butter', qty: 1, unit: 'tbsp' },
      { name: 'salt', qty: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Marinate chicken strips in yogurt, salt and spices 10 minutes; grill till done.',
      'Blend mint, yogurt and salt into a chutney-mayo.',
      'Toast bread with butter; layer chicken, onion and chutney.',
      'Press, halve, serve.',
    ],
  },
  {
    name: 'Overnight Oats',
    description: 'Creamy no-cook oats with fruit, set overnight in the fridge.',
    heritage: '', health_note: 'Fibre-rich and no-cook — breakfast that makes itself.',
    meal_types: ['breakfast'], diet: 'veg', servings: 2, prep_minutes: 10,
    protein_g: 11, carbs_g: 44, fat_g: 9, calories: 300,
    ingredients: [
      { name: 'oats', qty: 1, unit: 'cups' },
      { name: 'milk', qty: 1, unit: 'cups' },
      { name: 'yogurt', qty: 0.5, unit: 'cups' },
      { name: 'banana', qty: 1, unit: 'pcs' },
      { name: 'honey', qty: 1, unit: 'tbsp' },
      { name: 'mixed nuts', qty: 2, unit: 'tbsp' },
    ],
    steps: [
      'Mix oats, milk, yogurt and honey in a jar.',
      'Refrigerate overnight (at least 6 hours).',
      'Top with sliced banana and nuts in the morning.',
    ],
  },
  {
    name: 'Aloo Tikki Chaat',
    description: 'Crisp potato patties with dahi, chutneys and crunch.',
    heritage: '', health_note: 'Street-food joy at home — bake or air-fry the tikkis to keep it light.',
    meal_types: ['snack'], diet: 'veg', servings: 4, prep_minutes: 30,
    protein_g: 6, carbs_g: 38, fat_g: 12, calories: 280,
    ingredients: [
      { name: 'potato', qty: 5, unit: 'pcs' },
      { name: 'yogurt', qty: 1, unit: 'cups' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'chickpeas', qty: 0.5, unit: 'cups', note: 'boiled' },
      { name: 'tamarind chutney', qty: 3, unit: 'tbsp' },
      { name: 'chaat masala', qty: 1, unit: 'tsp' },
      { name: 'oil', qty: 3, unit: 'tbsp' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Mash boiled potatoes with salt; shape into tikkis and shallow-fry till crisp.',
      'Whisk dahi with a pinch of salt and sugar.',
      'Top tikkis with chickpeas, onion, dahi and chutneys.',
      'Dust with chaat masala and serve immediately.',
    ],
  },
  {
    name: 'Amritsari Fish Fry',
    description: 'Ajwain-spiced fish, crisped in mustard oil.',
    heritage: '', health_note: 'Fish is lean protein with good fats — the Amritsari way keeps it crisp, not greasy.',
    meal_types: ['dinner'], diet: 'nonveg', servings: 4, prep_minutes: 30,
    protein_g: 26, carbs_g: 14, fat_g: 14, calories: 290,
    ingredients: [
      { name: 'fish', qty: 750, unit: 'g' },
      { name: 'gram flour', qty: 0.5, unit: 'cups' },
      { name: 'carom seeds', qty: 1, unit: 'tsp' },
      { name: 'red chili powder', qty: 1, unit: 'tsp' },
      { name: 'turmeric', qty: 0.5, unit: 'tsp' },
      { name: 'lemon', qty: 1, unit: 'pcs' },
      { name: 'mustard oil', qty: 0.5, unit: 'cups' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Marinate fish with lemon, salt, spices and gram flour 20 minutes.',
      'Heat mustard oil till it smokes lightly, then cool a touch.',
      'Fry fish pieces till deep golden and crisp.',
      'Serve with onion rings and mint chutney.',
    ],
  },
  {
    name: 'Paneer Tikka',
    description: 'Charred marinated paneer with peppers and onion.',
    heritage: '', health_note: 'High-protein vegetarian grilling — tandoori flavour, no tandoor needed.',
    meal_types: ['snack'], diet: 'veg', servings: 4, prep_minutes: 25,
    protein_g: 17, carbs_g: 10, fat_g: 15, calories: 240,
    ingredients: [
      { name: 'paneer', qty: 400, unit: 'g' },
      { name: 'yogurt', qty: 0.5, unit: 'cups' },
      { name: 'capsicum', qty: 1, unit: 'pcs' },
      { name: 'onion', qty: 1, unit: 'pcs' },
      { name: 'tandoori masala', qty: 2, unit: 'tbsp' },
      { name: 'mustard oil', qty: 1, unit: 'tbsp' },
      { name: 'lemon', qty: 1, unit: 'pcs' },
      { name: 'salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Cube paneer and vegetables; marinate in spiced yogurt 20 minutes.',
      'Thread onto skewers.',
      'Grill or broil, turning, till charred at the edges.',
      'Squeeze lemon over and serve hot.',
    ],
  },
];

async function seedRecipes(pool) {
  let inserted = 0;
  for (const r of RECIPES) {
    const ex = await pool.query('SELECT id FROM rasoi_recipes WHERE name = $1', [r.name]);
    if (ex.rows.length) continue;
    const rr = await pool.query(
      `INSERT INTO rasoi_recipes
        (name, description, heritage, health_note, meal_types, diet, servings, prep_minutes,
         protein_g, carbs_g, fat_g, calories)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id`,
      [r.name, r.description, r.heritage, r.health_note, r.meal_types, r.diet,
       r.servings, r.prep_minutes, r.protein_g, r.carbs_g, r.fat_g, r.calories]
    );
    const id = rr.rows[0].id;
    for (const ing of r.ingredients) {
      await pool.query(
        `INSERT INTO rasoi_recipe_ingredients (recipe_id, name, qty, unit, note)
         VALUES ($1,$2,$3,$4,$5)`,
        [id, ing.name, ing.qty == null ? null : ing.qty, ing.unit || '', ing.note || '']
      );
    }
    let n = 1;
    for (const s of r.steps) {
      await pool.query(
        'INSERT INTO rasoi_recipe_steps (recipe_id, step_no, text) VALUES ($1,$2,$3)',
        [id, n++, s]
      );
    }
    inserted++;
  }
  return inserted;
}

async function recipeCount(pool) {
  const r = await pool.query('SELECT COUNT(*)::int AS n FROM rasoi_recipes');
  return r.rows[0].n;
}

module.exports = { RECIPES, seedRecipes, recipeCount };
